config/routes.rb
Rails.application.routes.draw do
  # root 'sessions#new'
  root 'main#index'

  get 'sessions/new'
  get 'main/index'

  get 'dashboard', to: 'users#index'

  resources :roles
  resources :tasks
  resources :quests
  resources :users
  resources :sessions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/quest.rb
class Quest < ApplicationRecord
	has_many :tasks
	has_many :user_role_quests
	has_many :users, through: :user_role_quest
	belongs_to :user, through: :user_role_quest

end

app/controllers/quests_controller.rb
class QuestsController < ApplicationController
  before_action :set_quest, only: [:show, :edit, :update, :destroy]
  before_action :require_logged_in

  # GET /quests
  # GET /quests.json
  def index
    @quests = current_user.quests.all
  end

  # GET /quests/1
  # GET /quests/1.json
  def show
  end

  # GET /quests/new
  def new
    @quest = current_user.quests.build
  end

  # GET /quests/1/edit
  def edit
  end

  # POST /quests
  # POST /quests.json
  def create
    @quest = current_user.quests.new(quest_params)

    respond_to do |format|
      if @quest.save
        format.html { redirect_to @quest, notice: 'Quest was successfully created.' }
        format.json { render :show, status: :created, location: @quest }
      else
        format.html { render :new }
        format.json { render json: @quest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quests/1
  # PATCH/PUT /quests/1.json
  def update
    respond_to do |format|
      if @quest.update(quest_params)
        format.html { redirect_to @quest, notice: 'Quest was successfully updated.' }
        format.json { render :show, status: :ok, location: @quest }
      else
        format.html { render :edit }
        format.json { render json: @quest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quests/1
  # DELETE /quests/1.json
  def destroy
    @quest.destroy
    respond_to do |format|
      format.html { redirect_to quests_url, notice: 'Quest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quest
      @quest = current_user.quests.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    # Shannan Qestion: Do we need to list everything as a param? Or can we remove a lot of these?
    def quest_params
      params.require(:quest).permit(:name, :description, :start_date, :start_time, :invite_msg, :start_msg, :final_msg)
    end
end

app/helpers/quests_helper.rb
module QuestsHelper
end

app/views/quests/_form.html.erb
<%= form_with(model: quest, local: true) do |form| %>
  <% if quest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quest.errors.count, "error") %> prohibited this quest from being saved:</h2>

      <ul>
      <% quest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :quest_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :quest_description %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.text_field :start_date, id: :quest_start_date %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.text_field :start_time, id: :quest_start_time %>
  </div>

  <div class="field">
    <%= form.label :invite_msg %>
    <%= form.text_field :invite_msg, id: :quest_invite_msg %>
  </div>

  <div class="field">
    <%= form.label :start_msg %>
    <%= form.text_field :start_msg, id: :quest_start_msg %>
  </div>

  <div class="field">
    <%= form.label :final_msg %>
    <%= form.text_field :final_msg, id: :quest_final_msg %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/quests/edit.html.erb
<h1>Editing Quest</h1>

<%= render 'form', quest: @quest %>

<%= link_to 'Show', @quest %> |
<%= link_to 'Back', quests_path %>

app/views/quests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Quests</h1>

<p>This page will show the list of quests the User is eligible to complete as a participant</p>


<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Start date</th>
      <th>Start time</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quests.each do |quest| %>
      <tr>
        <td><%= quest.name %></td>
        <td><%= quest.description %></td>
        <td><%= quest.start_date %></td>
        <td><%= quest.start_time %></td>
        <td><%= link_to 'Show', quest %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Back', quests_path %>
<%= link_to 'Home', users_path %>

app/views/quests/new.html.erb
<h1>New Quest</h1>
<%= form_for @quest do |f| %>

<p>
  <%= f.label :name %>
  <%= f.text_field :name %>
</p>

<p>
  <%= f.label :start_date %>
  <%= f.text_field :start_date %>
</p>

<p>
  <%= f.label :start_time %>
  <%= f.text_field :start_time %>
</p>

<p>
  <%= f.label :description %>
  <%= f.text_field :description %>
Note: This is a general description of the quest
</p>

<p>
  <%= f.label :invite_message %>
  <%= f.text_field :invite_message %>
Note: The participants will see this before they can access the quest so they
know what to expect. So include any items they might need, such as money,
umbrella, what to wear, etc.
</p>

<p>
  <%= f.label :invite_message %>
  <%= f.text_field :invite_message %>
Note: The participants will see this before they can access the quest so they
know what to expect. So include any items they might need, such as money,
umbrella, what to wear, etc.
</p>

<p>
  <%= f.label :start_message %>
  <%= f.text_field :start_message %>
Note: This message will be visible as soon as the start date/time pass. So this
is where you list the rules of the quest, the goals of the quest, anything you
want to get your participants motivated! Consider including a link to a secret/closed
Facebook group just for your quest, or setting a specific hastag for quest
photos/videos that are uploaded to social media sites, or tell them what to do
if they get stuck (e.g. Call You!).
</p>

<p>
  <%= f.label :final_message %>
  <%= f.text_field :final_message %>
Note: This is the final message the participants will see. So use this to
congratulate them, direct them to a specific location (e.g. party spot), or
remind them to upload their pics/videos to social media using a specific hashtag
or in a specific location (you can set up a private Facebook group for the quest,
for example).
</p>

<p>Leader:
<%= f.label :leader %>
<%= f.text_field :leader %>
<%= f.label :email %>
<%= f.text_field :email %>
</p>

<p>Participant:
<%= f.label :leader %>
<%= f.text_field :leader %>
<%= f.label :email %>
<%= f.text_field :email %>
</p>

<p>
  <%= f.submit %>
</p>
<% end %>


<%= link_to 'Back', quests_path %>

app/views/quests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quest Name:</strong>
  <%= @quest.name %>
</p>

<p>
  <strong>Notes from the Questmaster:</strong>
  <%= @quest.description %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @quest.start_date %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @quest.start_time %>
</p>

<p>This message will only show before the quest start date/time:</p>
<p>
  <strong>Invite msg:</strong>
  <%= @quest.invite_msg %>
</p>

<p>This message will show as soon as the quest start date/time is active:</p>
<p>
  <strong>Start msg:</strong>
  <%= @quest.start_msg %>
</p>

<p>Current Progress: [insert % complete or 9/10 tasks completed]</p>
<p>Set a link to take the Participant to the current active task</p>
<p>This link will be used in case a user gets dropped from the network or if a quest spans multiple days</p>


<%= link_to 'Back', quests_path %>

<p>This link needs to be scoped to be only tasks for this quest: </p>
<%= link_to 'Tasks', tasks_path %>